spring.application.name=skill-sync-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
# ===============================
# ? JWT CONFIG
# ===============================
jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}

# ===============================
# ? GOOGLE OAUTH CONFIG
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

google.client-id=${GOOGLE_CLIENT_ID}

# ==========================================
# OPENROUTER AI CONFIGURATION
# ==========================================

openrouter.api.key=${OPENROUTER_API_KEY}

# ==========================================
# TEST CONFIGURATION
# ==========================================

test.total-questions=10

test.duration-minutes=15

test.pass-percentage=70

test.retry-hours=24